# Generated by Django 4.2.21 on 2025-05-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], max_length=20)),
                ('type', models.CharField(choices=[('Payment', 'Payment'), ('Fine', 'Fine')], max_length=20)),
                ('session_url', models.URLField()),
                ('session_id', models.CharField(max_length=50)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrowing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.borrowing')),
            ],
        ),
    ]
