# Generated by Django 4.2.21 on 2025-05-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='borrowing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrowing.borrowing'),
        ),
    ]
