# Generated by Django 4.2.21 on 2025-05-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='borrowing',
            name='user_id',
        ),
    ]
