# Generated by Django 4.2.21 on 2025-05-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_borrowing_book_id_remove_borrowing_user_id'),
        ('payments', '0002_alter_payment_borrowing_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrowing',
        ),
    ]
