# Generated by Django 4.2.21 on 2025-05-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='actual_return',
            field=models.DateField(default=None),
        ),
    ]
