# Generated by Django 4.2.21 on 2025-05-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_alter_borrowing_actual_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='actual_return',
            field=models.DateField(blank=True, null=True),
        ),
    ]
