# Generated by Django 4.2.21 on 2025-05-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0004_alter_borrowing_actual_return'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='book_id',
            new_name='book',
        ),
    ]
