# Generated by Django 4.2.21 on 2025-05-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0005_rename_book_id_borrowing_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='user_id',
            new_name='user',
        ),
    ]
